<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>top.cheesetree.btx.framework</groupId>
        <artifactId>btx-framework-root</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>top.cheesetree.btx.project</groupId>
    <artifactId>btx-projects</artifactId>

    <packaging>pom</packaging>
    <modules>
        <module>btx-scheduler</module>
        <module>btx-dts</module>
        <module>btx-nacos</module>
    </modules>

    <properties>
    </properties>

    <dependencies>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>btx-framework-dependencies</artifactId>
                <version>${project.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>