<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.cheesetree.btx.framework</groupId>
        <artifactId>btx-framework-root</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>top.cheesetree.btx.framework.local</groupId>
    <artifactId>btx-framework-local</artifactId>
    <packaging>pom</packaging>
    <modules>
    </modules>

    <properties>
        <tongweb.version>7.0.E.6_P4</tongweb.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>btx-framework-dependencies</artifactId>
                <version>${project.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>