<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>top.cheesetree.btx.framework</groupId>
        <artifactId>btx-framework-parent</artifactId>
        <relativePath>../btx-framework-parent/pom.xml</relativePath>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>btx-framework</artifactId>
    <modules>
        <module>btx-framework-boot-cache</module>
        <module>btx-framework-boot</module>
        <module>btx-framework-boot-database-hikari</module>
        <module>btx-framework-core</module>
        <module>btx-framework-boot-session</module>
        <module>btx-framework-boot-security</module>
        <module>btx-framework-boot-security-shiro</module>
        <module>btx-framework-boot-database</module>
        <module>btx-framework-boot-web</module>
        <module>btx-framework-boot-webflux</module>
        <module>btx-framework-dependencies</module>
        <module>btx-framework-boot-security-shiro-redis</module>
        <module>btx-framework-boot-database-reactive</module>
        <module>btx-framework-boot-webflux-redis</module>
    </modules>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <url>https://github.com/cheesetree/btx-framework-root</url>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>
                    btx-framework-boot-cache
                </artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>
                    btx-framework-boot
                </artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>
                    btx-framework-core
                </artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>
                    btx-framework-boot-security
                </artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>
                    btx-framework-boot-web
                </artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.cheesetree.btx.framework.security</groupId>
                <artifactId>
                    btx-framework-boot-security-shiro
                </artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.cheesetree.btx.framework</groupId>
                <artifactId>btx-framework-boot-webflux</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>