<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>btx-scheduler</artifactId>
        <groupId>top.cheesetree.btx.project</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>btx-scheduler-xxl</artifactId>
    <groupId>top.cheesetree.btx.project.scheduler</groupId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <url>https://github.com/cheesetree/btx-framework-root</url>

    <properties>
        <xxl.job.version>3.4.2</xxl.job.version>
        <netty.version>4.1.132.Final</netty.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>${xxl.job.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>
                btx-framework-boot
            </artifactId>
        </dependency>
    </dependencies>

</project>
