<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.cheesetree.btx.project</groupId>
        <artifactId>btx-projects</artifactId>
        <version>1.2.6-SNAPSHOT</version>
    </parent>

    <artifactId>btx-demo</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot-cache</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework.database</groupId>
            <artifactId>btx-framework-boot-database-hikari</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot-session</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot-security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework.security</groupId>
            <artifactId>btx-framework-boot-security-shiro</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework.security</groupId>
            <artifactId>btx-framework-boot-security-shiro-redis</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot-database</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot-web</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <artifactId>btx-scheduler-xxl</artifactId>
            <groupId>top.cheesetree.btx.project.scheduler</groupId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <artifactId>btx-nacos</artifactId>
            <groupId>top.cheesetree.btx.project</groupId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>top.cheesetree.btx.framework.local</groupId>
            <artifactId>btx-framework-boot-web-tongweb</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.3.0.RELEASE</version>
                <configuration>
                    <outputDirectory>${outputDirectory}</outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <version>0.46.0</version>
                        <configuration>
                            <registry>10.116.0.51:30002</registry>
                            <authConfig>
                                <push>
                                    <username>deploy</username>
                                    <password>Zz@123456</password>
                                </push>
                            </authConfig>
                            <dockerHost>tcp://10.116.0.12:2375</dockerHost>
                            <images>
                                <image>
                                    <name>10.116.0.51:30002/nbzz/${project.artifactId}:${project.version}</name>
                                    <build>
                                        <from>
                                            10.116.0.51:30002/nbzz/debian-jdk8:latest
                                        </from>
                                        <ports>
                                            <port>9000/tcp</port>
                                        </ports>
                                        <entryPoint>
                                            <shell>java -jar /data/${project.artifactId}-${project.version}.jar --server.port=9000
                                            </shell>
                                        </entryPoint>
                                        <assemblies>
                                            <assembly>
                                                <mode>dir</mode>
                                                <targetDir>/data</targetDir>
                                                <descriptorRef>artifact</descriptorRef>
                                            </assembly>
                                        </assemblies>
                                    </build>
                                </image>
                            </images>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>