<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.cheesetree.btx.framework.local</groupId>
        <artifactId>btx-framework-local</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>btx-framework-boot-web-tongweb</artifactId>

    <properties>
        <com.tongweb.springboot.version>2.x.0.RELEASE_P1</com.tongweb.springboot.version>
        <com.tongweb.embed.version>7.0.E.2_P1</com.tongweb.embed.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>top.cheesetree.btx.framework</groupId>
            <artifactId>btx-framework-boot-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.tongweb.springboot</groupId>-->
<!--            <artifactId>tongweb-spring-boot-starter-2.x</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.tongweb</groupId>-->
<!--            <artifactId>tongweb-embed-core</artifactId>-->
<!--        </dependency>-->
    </dependencies>
</project>